### ISSUE TITLE
Setup Continuous Integration on Travis CI

### ISSUE THREAD

**Issue by BartVandewoestyne** [BartVandewoestyne/Effective-Modern-Cpp#5]
We should setup Continuous Integration so we can easily test if everything works under several different environments.  See https://travis-ci.org/

**Comment by BartVandewoestyne** [comment]
I've started something at https://travis-ci.org/BartVandewoestyne/Effective-Modern-Cpp/ but I was not able to figure out how to get at least Boost 1.56.  I _think_ we need at least Boost 1.56 to have support for Boost.TypeIndex (see Item 4).  If anybody knows how to get Boost 1.56 on Travis CI, please let me know or adapt the .travis.yml file.

**Comment by yoyonel** [comment]
Hi Bart !
Yes you're right, we need Boost 1.56. (for the Item 4 and TypeIndex boost support).
You can look into my Travis CI depot, i managed to build my fork depot (master branch):
- travis file present in my master branch: [.travis.yml](https://github.com/yoyonel/Effective-Modern-Cpp/blob/master/.travis.yml)
- Travis build result: [Build #13](https://travis-ci.org/yoyonel/Effective-Modern-Cpp/builds/131352841)

The trick was to added a custom build of the boost's version you need (1.56 in our case).
It's not difficult after all, but it was my first time with Travis CI ;-)

**Comment by BartVandewoestyne** [comment]
Our Travis CI builds now work for g++ 4.9 and 5.0, and also for clang++ 3.6.  Only clang++ 3.7 is still failing.  I consider 3/4 a succes and am therefore closing this issue.  Travis CI seems functional now.

**Comment by yoyonel** [comment]
Oki doki, i will look soon for clang++ 3.7.
Keep in touch ;)

ps: It's strange ... in my travis account, i have a full functional result even for clang++ 3.7 ... MmMMMmm
=> https://travis-ci.org/yoyonel/Effective-Modern-Cpp/builds/131356025

**Comment by yoyonel** [comment]
Oki i see the problem. 
I have the same on my work computer.
The apt for llvm seems to be changed, i need to update the apt url for precise (or other ubuntu releases) and llvm.
